// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanProject;

/************************************************************/
/**
 * 
 */
public class Edge {
	/**
	 * 
	 */
	private int edgeID;
	/**
	 * 
	 */
	public Player occupant;

	/**
	 * 
	 * @param p 
	 */
	public void setOccupant(Player p) {
	}
}
