// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanProject;

/************************************************************/
/**
 * 
 */
public interface IBoardGraph {
	/**
	 * 
	 * @param nodeID 
	 * @return 
	 */
	public int[] getAdjacentNodes(int nodeID);

	/**
	 * 
	 * @param nodeID 
	 * @return 
	 */
	public int[] getAdjacentEdges(int nodeID);
}
