// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanProject;

/************************************************************/
/**
 * 
 */
public interface IRandomDice {
	/**
	 * 
	 * @return 
	 */
	public int roll();
}
