// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package UMLDesign.CatanProject.com.mycompany.app;

/************************************************************/
/**
 * 
 */
public enum BuildingType {
	/**
	 * 
	 */
	NONE,
	/**
	 * 
	 */
	SETTLEMENT,
	/**
	 * 
	 */
	CITY,
	/**
	 * 
	 */
	ROAD;
}
