// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package UMLDesign.CatanProject.com.mycompany.app;

import java.io.IOException;

/************************************************************/
/**
 * Parser for reading configuration files for the Catan simulator
 */
public class ConfigParser {
	/**
	 * Read the maximum number of turns from a configuration file Expected format: "turns: <integer>" @param filename Path to the configuration file @return The maximum number of turns (1-8192) @throws IOException If file cannot be read @throws IllegalArgumentException If format is invalid or value is out of range
	 * @return 
	 * @param filename 
	 */
	public static Integer readMaxTurns(String filename) throws IOException {
		
	}
}
