// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package UMLDesign.CatanProject.com.mycompany.app;

/************************************************************/
/**
 * 
 */
public class Edge {
	/**
	 * Unique identifier for this edge
	 */
	private Integer edgeID;
	/**
	 * Player who has built a road on this edge (null if no road)
	 */
	private Player occupant;

	/**
	 * Constructor for Edge @param edgeID Unique edge identifier
	 * @param edgeID 
	 */
	public Edge(Integer edgeID) {
		
	}

	/**
	 * Get the edge ID @return The edge's unique identifier
	 * @return 
	 */
	public Integer getEdgeID() {
		
	}

	/**
	 * Get the occupying player @return The player who owns the road, or null if no road
	 * @return 
	 */
	public Player getOccupant() {
		
	}

	/**
	 * Set the occupant of this edge (build a road) @param p Player who will build a road on this edge
	 * @param p 
	 */
	public void setOccupant(Player p) {
		
	}

	/**
	 * Check if this edge has a road @return true if any player has built a road on this edge
	 * @return 
	 */
	public Boolean hasRoad() {
		
	}

	/**
	 * Check if this edge has a road owned by specific player @param playerID The player ID to check @return true if this player has a road on this edge
	 * @return 
	 * @param playerID 
	 */
	public Boolean hasRoadBy(Integer playerID) {
		
	}

	/**
	 * Build a road on this edge @param player The player building the road
	 * @param player 
	 */
	public void buildRoad(Player player) {
		
	}
}
