// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package UMLDesign.CatanProject.com.mycompany.app;

/************************************************************/
/**
 * 
 */
public enum TileType {
	/**
	 * 
	 */
	WOOD,
	/**
	 * 
	 */
	BRICK,
	/**
	 * 
	 */
	WHEAT,
	/**
	 * 
	 */
	SHEEP,
	/**
	 * 
	 */
	ORE,
	/**
	 * 
	 */
	DESERT;

	/**
	 * Get the resource type produced by this tile type @return ResourceType, or null for DESERT
	 * @return 
	 */
	public ResourceType getResourceType() {
		
	}
}
