// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanProject;

/************************************************************/
/**
 * 
 */
public class ActionLogger {
	/**
	 * 
	 * @param round 
	 * @param playerID 
	 * @param action 
	 */
	public void logAction(int round, int playerID, String action) {
	}
}
