// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.mycompany.app;

/************************************************************/
/**
 * 
 */
public class ActionLogger {
	/**
	 * Log an action to console in the specified format: [round] / [playerID]: action
	 * @param round Current round number
	 * @param playerID Player taking the action
	 * @param action Description of the action taken
	 */
	public void logAction(int round, int playerID, String action) {
		System.out.println("[" + round + "] / [" + playerID + "]: " + action);
	}
}
