// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.mycompany.app;
import java.util.*;
import java.util.Collection;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	private Map<Integer, HexTile> tiles;
	/**
	 * 
	 */
	private Map<Integer, Node>  nodes;
	/**
	 * 
	 */
	private Map<Integer, Edge> edges;
	/**
	 * 
	 */
	private IBoardGraph topology;

	/**
	 * Constructor for Board
	 * @param topology Board topology defining node and edge adjacencies
	 */
	public Board(IBoardGraph topology) {
		this.topology = topology;
		this.tiles = new HashMap<>();
		this.nodes = new HashMap<>();
		this.edges = new HashMap<>();
		initializeBoard();
	}

	/**
	 * Initialize the board with a hardcoded valid Catan configuration
	 * Creates 19 tiles, 54 nodes, and 72 edges
	 */
	private void initializeBoard() {
		// Initialize tiles with standard Catan distribution
		// 4 WHEAT, 4 SHEEP, 4 WOOD, 3 BRICK, 3 ORE, 1 DESERT
		// Number tokens: 2-12 (excluding 7), with standard frequency

		// Center tile
		tiles.put(0, new HexTile(0, TileType.WHEAT, 6));

		// Inner ring (6 tiles)
		tiles.put(1, new HexTile(1, TileType.WOOD, 3));
		tiles.put(2, new HexTile(2, TileType.BRICK, 8));
		tiles.put(3, new HexTile(3, TileType.SHEEP, 4));
		tiles.put(4, new HexTile(4, TileType.ORE, 9));
		tiles.put(5, new HexTile(5, TileType.WHEAT, 5));
		tiles.put(6, new HexTile(6, TileType.SHEEP, 10));

		// Outer ring (12 tiles)
		tiles.put(7, new HexTile(7, TileType.WOOD, 11));
		tiles.put(8, new HexTile(8, TileType.WHEAT, 12));
		tiles.put(9, new HexTile(9, TileType.SHEEP, 2));
		tiles.put(10, new HexTile(10, TileType.BRICK, 6));
		tiles.put(11, new HexTile(11, TileType.DESERT, 0));  // Desert has no token
		tiles.put(12, new HexTile(12, TileType.ORE, 3));
		tiles.put(13, new HexTile(13, TileType.WOOD, 8));
		tiles.put(14, new HexTile(14, TileType.BRICK, 4));
		tiles.put(15, new HexTile(15, TileType.SHEEP, 5));
		tiles.put(16, new HexTile(16, TileType.WOOD, 9));
		tiles.put(17, new HexTile(17, TileType.ORE, 10));
		tiles.put(18, new HexTile(18, TileType.WHEAT, 11));

		// Initialize all 54 nodes as empty
		for (int i = 0; i < 54; i++) {
			nodes.put(i, new Node(i));
		}

		// Initialize all 72 edges as empty
		for (int i = 0; i < 72; i++) {
			edges.put(i, new Edge(i));
		}
	}

	/**
	 * Get a specific node by ID
	 * @param nodeID The node identifier
	 * @return The Node object, or null if not found
	 */
	public Node getNode(int nodeID) {
		return nodes.get(nodeID);
	}

	/**
	 * Get a specific edge by ID
	 * @param edgeID The edge identifier
	 * @return The Edge object, or null if not found
	 */
	public Edge getEdge(int edgeID) {
		return edges.get(edgeID);
	}

	/**
	 * Get a specific tile by ID
	 * @param tileID The tile identifier
	 * @return The HexTile object, or null if not found
	 */
	public HexTile getTile(int tileID) {
		return tiles.get(tileID);
	}

	/**
	 * Get all tiles on the board
	 * @return Collection of all HexTiles
	 */
	public Collection<HexTile> getAllTiles() {
		return tiles.values();
	}

	/**
	 * Get all nodes on the board
	 * @return Collection of all Nodes
	 */
	public Collection<Node> getAllNodes() {
		return nodes.values();
	}

	/**
	 * Get all edges on the board
	 * @return Collection of all Edges
	 */
	public Collection<Edge> getAllEdges() {
		return edges.values();
	}

	/**
	 * Get the board topology
	 * @return The IBoardGraph defining adjacencies
	 */
	public IBoardGraph getTopology() {
		return topology;
	}
}
