// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.mycompany.app;
import com.mycompany.app.validators.*;
import com.mycompany.app.services.*;
import java.util.*;

/************************************************************/
/**
 * Main game engine that implements game rules and validates player actions.
 * Implements the IGameController interface to provide a clean API for players.
 */
public class CatanEngine implements IGameController {
	/**
	 * Game board with tiles, nodes, and edges
	 */
	private Board board;
	/**
	 * Dice for rolling
	 */
	private IRandomDice dice;
	/**
	 * List of players in the game
	 */
	private List<Player> players;
	/**
	 * Validator for settlement placement
	 */
	private SettlementValidator settlementValidator;
	/**
	 * Validator for road placement
	 */
	private RoadValidator roadValidator;
	/**
	 * Service for distributing resources
	 */
	private ResourceDistributor resourceDistributor;
	/**
	 * Service for building placement
	 */
	private BuildingService buildingService;

	/**
	 * Constructor for CatanEngine
	 * @param board The game board
	 * @param dice Dice implementation
	 */
	public CatanEngine(Board board, IRandomDice dice) {
		this.board = board;
		this.dice = dice;
		this.players = new ArrayList<>();

		// Initialize validators
		this.settlementValidator = new SettlementValidator(board);
		this.roadValidator = new RoadValidator(board, board.getTopology());

		// Initialize services
		this.resourceDistributor = new ResourceDistributor(board, board.getTopology());
		this.buildingService = new BuildingService(board, settlementValidator, roadValidator);
	}

	/**
	 * Set the players for this game
	 * @param players List of players
	 */
	public void setPlayers(List<Player> players) {
		this.players = players;
	}

	/**
	 * Roll the dice
	 * @return The dice roll result (2-12)
	 */
	public int rollDice() {
		return dice.roll();
	}

	/**
	 * Distribute resources based on dice roll
	 * @param diceRoll The number rolled
	 * @param players List of all players
	 */
	public void distributeResources(int diceRoll, List<Player> players) {
		resourceDistributor.distribute(diceRoll, players);
	}

	@Override
	public int[] getValidSettlementLocations(int playerID) {
		boolean isInitialPlacement = getTotalBuildings(playerID) == 0;
		return settlementValidator.getValidLocations(playerID, isInitialPlacement);
	}

	/**
	 * Get total buildings for a player
	 */
	private int getTotalBuildings(int playerID) {
		int count = 0;
		for (Node node : board.getAllNodes()) {
			if (node.getOccupant() != null &&
			    node.getOccupant().getPlayerID() == playerID &&
			    node.getType() != BuildingType.NONE) {
				count++;
			}
		}
		return count;
	}

	@Override
	public int[] getValidRoadLocations(int playerID) {
		return roadValidator.getValidLocations(playerID);
	}

	@Override
	public boolean requestBuildSettlement(int playerID, int nodeID) {
		Player player = getPlayer(playerID);
		if (player == null) return false;
		return buildingService.buildSettlement(playerID, nodeID, player);
	}

	@Override
	public boolean requestBuildRoad(int playerID, int edgeID) {
		Player player = getPlayer(playerID);
		if (player == null) return false;
		return buildingService.buildRoad(playerID, edgeID, player);
	}

	/**
	 * Request to build a city (upgrade settlement)
	 * @param playerID Player making the request
	 * @param nodeID Node location
	 * @return true if successful, false otherwise
	 */
	public boolean requestBuildCity(int playerID, int nodeID) {
		Player player = getPlayer(playerID);
		if (player == null) return false;
		return buildingService.buildCity(playerID, nodeID, player);
	}

	/**
	 * Get a player by ID
	 * @param playerID The player's ID
	 * @return The Player object, or null if not found
	 */
	private Player getPlayer(int playerID) {
		if (players == null) return null;

		return players.stream()
			.filter(p -> p.getPlayerID() == playerID)
			.findFirst()
			.orElse(null);
	}

	/**
	 * Get the board
	 * @return The game board
	 */
	public Board getBoard() {
		return board;
	}
}
