// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.mycompany.app;

/************************************************************/
/**
 * 
 */
public class Edge {
	/**
	 * Unique identifier for this edge
	 */
	private int edgeID;
	/**
	 * Player who has built a road on this edge (null if no road)
	 */
	private Player occupant;

	/**
	 * Constructor for Edge
	 * @param edgeID Unique edge identifier
	 */
	public Edge(int edgeID) {
		this.edgeID = edgeID;
		this.occupant = null;
	}

	/**
	 * Get the edge ID
	 * @return The edge's unique identifier
	 */
	public int getEdgeID() {
		return edgeID;
	}

	/**
	 * Get the occupying player
	 * @return The player who owns the road, or null if no road
	 */
	public Player getOccupant() {
		return occupant;
	}

	/**
	 * Set the occupant of this edge (build a road)
	 * @param p Player who will build a road on this edge
	 */
	public void setOccupant(Player p) {
		this.occupant = p;
	}

	/**
	 * Check if this edge has a road
	 * @return true if any player has built a road on this edge
	 */
	public boolean hasRoad() {
		return occupant != null;
	}

	/**
	 * Check if this edge has a road owned by specific player
	 * @param playerID The player ID to check
	 * @return true if this player has a road on this edge
	 */
	public boolean hasRoadBy(int playerID) {
		return occupant != null && occupant.getPlayerID() == playerID;
	}

	/**
	 * Build a road on this edge
	 * @param player The player building the road
	 */
	public void buildRoad(Player player) {
		this.occupant = player;
	}
}
