// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.mycompany.app;

import java.io.FileWriter;
import java.io.IOException;
import java.util.*;

/************************************************************/
/**
 * Observer that exports the game state to external JSON files.
 * Implements IObserver to react to game state changes.
 */
public class GameStateObserver implements IObserver {
    /**
     * File path for the initial board configuration
     */
    private String initFilePath;
    /**
     * File path for the current game state
     */
    private String stateFilePath;
    /**
     * Reference to the game engine
     */
    public CatanEngine engine;

    /**
     * Constructor for GameStateObserver
     * 
     * @param controller Game controller reference (must be a CatanEngine)
     */
    public GameStateObserver(IGameController controller) {
        this.engine = (CatanEngine) controller;
        this.initFilePath = "initial_board.json";
        this.stateFilePath = "game_state.json";
        exportInitialBoard();
    }

    /**
     * Called when the game state changes. Exports the current state to JSON.
     */
    @Override
    public void update() {
        exportGameState();
    }

    /**
     * Export the initial board configuration to a JSON file.
     * Writes tile types, number tokens, and board layout.
     */
    private void exportInitialBoard() {
        StringBuilder json = new StringBuilder();
        json.append("{\n");
        json.append("  \"type\": \"initial_board\",\n");
        json.append("  \"tiles\": [\n");

        Board board = engine.getBoard();
        Collection<HexTile> tiles = board.getAllTiles();
        int tileCount = 0;
        int totalTiles = tiles.size();

        for (HexTile tile : tiles) {
            json.append("    {\n");
            json.append("      \"tileID\": ").append(tile.getTileID()).append(",\n");
            json.append("      \"type\": \"").append(tile.getType()).append("\",\n");
            json.append("      \"numberToken\": ").append(tile.getNumberToken()).append("\n");
            json.append("    }");
            tileCount++;
            if (tileCount < totalTiles) {
                json.append(",");
            }
            json.append("\n");
        }

        json.append("  ]\n");
        json.append("}\n");

        writeToFile(initFilePath, json.toString());
    }

    /**
     * Export the current game state to a JSON file.
     * Writes node occupancy, edge roads, and player resources.
     */
    private void exportGameState() {
        StringBuilder json = new StringBuilder();
        json.append("{\n");
        json.append("  \"type\": \"game_state\",\n");

        Board board = engine.getBoard();

        // Export nodes
        json.append("  \"nodes\": [\n");
        Collection<Node> nodes = board.getAllNodes();
        int nodeCount = 0;
        int totalNodes = nodes.size();

        for (Node node : nodes) {
            json.append("    {\n");
            json.append("      \"nodeID\": ").append(node.getNodeID()).append(",\n");
            json.append("      \"type\": \"").append(node.getType()).append("\",\n");
            if (node.getOccupant() != null) {
                json.append("      \"occupant\": ").append(node.getOccupant().getPlayerID()).append("\n");
            } else {
                json.append("      \"occupant\": null\n");
            }
            json.append("    }");
            nodeCount++;
            if (nodeCount < totalNodes) {
                json.append(",");
            }
            json.append("\n");
        }
        json.append("  ],\n");

        // Export edges
        json.append("  \"edges\": [\n");
        Collection<Edge> edges = board.getAllEdges();
        int edgeCount = 0;
        int totalEdges = edges.size();

        for (Edge edge : edges) {
            json.append("    {\n");
            json.append("      \"edgeID\": ").append(edge.getEdgeID()).append(",\n");
            json.append("      \"hasRoad\": ").append(edge.hasRoad()).append(",\n");
            if (edge.getOccupant() != null) {
                json.append("      \"occupant\": ").append(edge.getOccupant().getPlayerID()).append("\n");
            } else {
                json.append("      \"occupant\": null\n");
            }
            json.append("    }");
            edgeCount++;
            if (edgeCount < totalEdges) {
                json.append(",");
            }
            json.append("\n");
        }
        json.append("  ]\n");

        json.append("}\n");

        writeToFile(stateFilePath, json.toString());
    }

    /**
     * Write a string to a file
     * 
     * @param filePath Path to the output file
     * @param content  Content to write
     */
    private void writeToFile(String filePath, String content) {
        try (FileWriter writer = new FileWriter(filePath)) {
            writer.write(content);
        } catch (IOException e) {
            System.err.println("Error writing to " + filePath + ": " + e.getMessage());
        }
    }
}
