// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.mycompany.app;

import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Queue;
import java.util.Set;

/************************************************************/
/**
 * 
 */
public class GameStateObserver implements IObserver {
	/**
	 * 
	 */
	private String initFilePath;
	/**
	 * 
	 */
	private String stateFilePath;
	/**
	 * 
	 */
	public CatanEngine engine;

	/**
	 * 
	 */
	@Override
	public void update() {
        exportInitialBoard();
        exportGameState();
	}

	/**
	 * 
	 * @param engine 
	 */
	public GameStateObserver(CatanEngine engine) {
		this.engine = engine;
        // Paths are resolved relative to the working directory at runtime.
        // When running the JAR from Part4/CatanProject/target,
        // ../../../visualize points back to the repo's visualize folder.
        this.initFilePath = "../../../visualize/base_map.json";
        this.stateFilePath = "../../../visualize/state.json";
        this.engine.attach(this);
	}

	private static final int[][] TILE_COORDS = new int[][]{
		// center
		{0, 0, 0},
		// first layer
		{1, -1, 0},
		{0, -1, 1},
		{-1, 0, 1},
		{-1, 1, 0},
		{0, 1, -1},
		{1, 0, -1},
		// second layer
		{2, -2, 0},
		{1, -2, 1},
		{0, -2, 2},
		{-1, -1, 2},
		{-2, 0, 2},
		{-2, 1, 1},
		{-2, 2, 0},
		{-1, 2, -1},
		{0, 2, -2},
		{1, 1, -2},
		{2, 0, -2},
		{2, -1, -1},
	};

	/**
	 * 
	 */
	private void exportInitialBoard() {
		Board board = engine.getBoard();

		StringBuilder json = new StringBuilder();
		json.append("{\n");
		json.append("  \"tiles\": [\n");

		for (int tileID = 0; tileID < TILE_COORDS.length; tileID++) {
			HexTile tile = board.getTile(tileID);
			if (tile == null) {
				continue;
			}

			int[] coords = TILE_COORDS[tileID];
			int q = coords[0];
			int s = coords[1];
			int r = coords[2];

			TileType type = tile.getType();
			boolean isDesert = type == TileType.DESERT;

			json.append("    { \"q\": ").append(q)
				.append(", \"s\": ").append(s)
				.append(", \"r\": ").append(r)
				.append(", \"resource\": ");

			if (isDesert) {
				json.append("null, \"number\": null }");
			} else {
				json.append("\"").append(type.name()).append("\", \"number\": ")
					.append(tile.getNumberToken()).append(" }");
			}

			if (tileID < TILE_COORDS.length - 1) {
				json.append(",\n");
			} else {
				json.append("\n");
			}
		}

		json.append("  ]\n");
		json.append("}\n");

		writeToFile(initFilePath, json.toString());
	}

	/**
	 * 
	 */
	private void exportGameState() {
		Board board = engine.getBoard();
		IBoardGraph topology = board.getTopology();

		StringBuilder json = new StringBuilder();
		json.append("{\n");

		// Roads: export in BFS order from settlements so visualizer receives valid dependency order
		json.append("  \"roads\": [\n");
		List<int[]> orderedRoads = collectRoadsInBfsOrder(board, topology);
		for (int i = 0; i < orderedRoads.size(); i++) {
			int[] r = orderedRoads.get(i);
			if (i > 0) {
				json.append(",\n");
			}
			json.append("    { \"a\": ").append(r[1])
				.append(", \"b\": ").append(r[2])
				.append(", \"owner\": \"").append(getColorForPlayer(r[0])).append("\" }");
		}
		json.append("\n  ],\n");

		// Buildings
		json.append("  \"buildings\": [\n");
		boolean firstBuilding = true;
		for (Node node : board.getAllNodes()) {
			if (node.getOccupant() == null) {
				continue;
			}
			BuildingType type = node.getType();
			if (type != BuildingType.SETTLEMENT && type != BuildingType.CITY) {
				continue;
			}

			if (!firstBuilding) {
				json.append(",\n");
			}
			firstBuilding = false;

			String ownerColor = getColorForPlayer(node.getOccupant().getPlayerID());
			json.append("    { \"node\": ").append(node.getNodeID())
				.append(", \"owner\": \"").append(ownerColor).append("\"")
				.append(", \"type\": \"").append(type.name()).append("\" }");
		}
		json.append("\n  ]\n");
		json.append("}\n");

		writeToFile(stateFilePath, json.toString());
	}

	/**
	 * Collect roads in BFS order from each player's settlements/cities so the visualizer receives
	 * a valid dependency order (each road after the settlement or road it connects to).
	 */
	private List<int[]> collectRoadsInBfsOrder(Board board, IBoardGraph topology) {
		List<int[]> orderedRoads = new ArrayList<>();
		for (int playerID = 0; playerID < 4; playerID++) {
			Set<Integer> buildingNodes = new HashSet<>();
			for (Node node : board.getAllNodes()) {
				if (node.getOccupant() != null &&
						node.getOccupant().getPlayerID() == playerID &&
						node.getType() != BuildingType.NONE) {
					buildingNodes.add(node.getNodeID());
				}
			}
			Set<Integer> visitedNodes = new HashSet<>(buildingNodes);
			Set<Integer> outputEdgeIds = new HashSet<>();
			Queue<Integer> queue = new ArrayDeque<>(buildingNodes);
			while (!queue.isEmpty()) {
				int nodeID = queue.poll();
				int[] adjEdges = topology.getAdjacentEdges(nodeID);
				for (int edgeID : adjEdges) {
					if (outputEdgeIds.contains(edgeID)) continue;
					Edge edge = board.getEdge(edgeID);
					if (!edge.hasRoad() || edge.getOccupant().getPlayerID() != playerID) continue;
					int[] ep = topology.getEdgeEndpoints(edgeID);
					if (ep == null || ep.length != 2) continue;
					outputEdgeIds.add(edgeID);
					orderedRoads.add(new int[]{playerID, ep[0], ep[1]});
					int other = ep[0] == nodeID ? ep[1] : ep[0];
					if (!visitedNodes.contains(other)) {
						visitedNodes.add(other);
						queue.add(other);
					}
				}
			}
		}
		return orderedRoads;
	}

	private String getColorForPlayer(int playerID) {
		int idx = Math.floorMod(playerID, 4);
		switch (idx) {
			case 0: return "RED";
			case 1: return "BLUE";
			case 2: return "ORANGE";
			case 3: return "WHITE";
			default: return "RED";
		}
	}

	private void writeToFile(String path, String contents) {
		try (FileWriter writer = new FileWriter(path)) {
			writer.write(contents);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}
