// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanProject;

/************************************************************/
/**
 * 
 */
public class HexTile {
	/**
	 * 
	 */
	private int tileID;
	/**
	 * 
	 */
	private TileType type;
	/**
	 * 
	 */
	private int numberToken;
}
