// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.mycompany.app;

/************************************************************/
/**
 * 
 */
public class HexTile {
	/**
	 * Unique identifier for this tile
	 */
	private int tileID;
	/**
	 * Type of resource this tile produces
	 */
	private TileType type;
	/**
	 * Number token on this tile (2-12, or 0 for desert)
	 */
	private int numberToken;

	/**
	 * Constructor for HexTile
	 * @param tileID Unique tile identifier
	 * @param type Resource type of this tile
	 * @param numberToken Number token (2-12, or 0 for desert)
	 */
	public HexTile(int tileID, TileType type, int numberToken) {
		this.tileID = tileID;
		this.type = type;
		this.numberToken = numberToken;
	}

	/**
	 * Get the tile ID
	 * @return The tile's unique identifier
	 */
	public int getTileID() {
		return tileID;
	}

	/**
	 * Get the tile type
	 * @return The resource type of this tile
	 */
	public TileType getType() {
		return type;
	}

	/**
	 * Get the number token
	 * @return The number token on this tile
	 */
	public int getNumberToken() {
		return numberToken;
	}
}
