// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.mycompany.app;

/************************************************************/
/**
 * 
 */
public interface IBoardGraph {
	/**
	 * 
	 * @param nodeID 
	 * @return 
	 */
	public int[] getAdjacentNodes(int nodeID);

	/**
	 *
	 * @param nodeID
	 * @return
	 */
	public int[] getAdjacentEdges(int nodeID);

	/**
	 * Get the two endpoint nodes of an edge
	 * @param edgeID The edge identifier
	 * @return Array of two node IDs, or empty array if not found
	 */
	public int[] getEdgeEndpoints(int edgeID);

	/**
	 * Get nodes adjacent to a specific tile
	 * @param tileID The tile identifier (0-18)
	 * @return Array of node IDs surrounding this tile
	 */
	public int[] getTileNodes(int tileID);
}
