// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package main.java.com.mycompany.app;

/************************************************************/
/**
 * 
 */
public interface IGameController {
	/**
	 * 
	 * @param playerID 
	 * @return 
	 */
	public int[] getValidSettlementLocations(int playerID);

	/**
	 * 
	 * @param playerID 
	 * @return 
	 */
	public int[] getValidRoadLocations(int playerID);

	/**
	 * 
	 * @param playerID 
	 * @param nodeID 
	 * @return 
	 */
	public boolean requestBuildSettlement(int playerID, int nodeID);

	/**
	 * 
	 * @param playerID 
	 * @param edgeID 
	 * @param Parameter1 
	 */
	public boolean requestBuildRoad(int playerID, int edgeID);
}
