// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.mycompany.app;

/************************************************************/
/**
 * 
 */
public interface IObserver {
	/**
	 * 
	 */
	public void update();
}
