// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.mycompany.app;

/************************************************************/
/**
 * 
 */
public interface IRandomDice {
	/**
	 * 
	 * @return 
	 */
	public Integer roll();
}
