// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.mycompany.app;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * Unique identifier for this node
	 */
	private int nodeID;
	/**
	 * Type of building on this node (NONE, SETTLEMENT, or CITY)
	 */
	private BuildingType type;
	/**
	 * Player who owns the building on this node (null if unoccupied)
	 */
	private Player occupant;

	/**
	 * Constructor for Node
	 * @param nodeID Unique node identifier
	 */
	public Node(int nodeID) {
		this.nodeID = nodeID;
		this.type = BuildingType.NONE;
		this.occupant = null;
	}

	/**
	 * Get the node ID
	 * @return The node's unique identifier
	 */
	public int getNodeID() {
		return nodeID;
	}

	/**
	 * Get the building type on this node
	 * @return The type of building (NONE, SETTLEMENT, or CITY)
	 */
	public BuildingType getType() {
		return type;
	}

	/**
	 * Get the occupying player
	 * @return The player who owns the building, or null if unoccupied
	 */
	public Player getOccupant() {
		return occupant;
	}

	/**
	 * Set the occupant and building type on this node
	 * @param p Player who will occupy this node
	 * @param t Type of building to place
	 */
	public void setOccupant(Player p, BuildingType t) {
		this.occupant = p;
		this.type = t;
	}

	/**
	 * Check if this node is occupied by any player
	 * @return true if there's a building on this node
	 */
	public boolean isOccupied() {
		return type != BuildingType.NONE && occupant != null;
	}

	/**
	 * Check if this node is occupied by a specific player
	 * @param playerID The player ID to check
	 * @return true if this player occupies this node
	 */
	public boolean isOccupiedBy(int playerID) {
		return occupant != null && occupant.getPlayerID() == playerID;
	}

	/**
	 * Build a settlement on this node
	 * @param player The player building the settlement
	 */
	public void buildSettlement(Player player) {
		this.occupant = player;
		this.type = BuildingType.SETTLEMENT;
	}

	/**
	 * Upgrade settlement to city on this node
	 * @param player The player upgrading (must already own settlement)
	 */
	public void upgradeToCity(Player player) {
		if (this.type == BuildingType.SETTLEMENT && this.occupant == player) {
			this.type = BuildingType.CITY;
		}
	}

	/**
	 * Check if this is a settlement owned by the given player
	 * @param playerID The player ID to check
	 * @return true if this node has a settlement owned by the player
	 */
	public boolean hasSettlementBy(int playerID) {
		return type == BuildingType.SETTLEMENT &&
		       occupant != null &&
		       occupant.getPlayerID() == playerID;
	}
}
