// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.mycompany.app;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;

/************************************************************/
/**
 * Abstract base class for all player types in the game.
 * Manages resources, victory points, and defines abstract methods for player
 * behavior.
 */
public abstract class Player {
	/**
	 * Unique identifier for this player
	 */
	protected int playerID;
	/**
	 * Current victory points for this player
	 */
	protected int victoryPoints;
	/**
	 * Resources owned by this player (map of resource type to quantity)
	 */
	protected Map<ResourceType, Integer> resources;

	/**
	 * Constructor for Player
	 * 
	 * @param playerID Unique player identifier
	 */
	public Player(int playerID) {
		this.playerID = playerID;
		this.victoryPoints = 0;
		this.resources = new HashMap<>();

		// Initialize all resource types to 0
		for (ResourceType type : ResourceType.values()) {
			resources.put(type, 0);
		}
	}

	/**
	 * Get the player's ID
	 * 
	 * @return The player's unique identifier
	 */
	public int getPlayerID() {
		return playerID;
	}

	/**
	 * Get the player's current victory points
	 * 
	 * @return Current victory points
	 */
	public int getVictoryPoints() {
		return victoryPoints;
	}

	/**
	 * Add victory points to this player
	 * 
	 * @param points Number of points to add
	 */
	public void addVictoryPoints(int points) {
		this.victoryPoints += points;
	}

	/**
	 * Add resources to this player's inventory
	 * 
	 * @param type   Type of resource to add
	 * @param amount Amount to add
	 */
	public void addResource(ResourceType type, int amount) {
		resources.put(type, resources.get(type) + amount);
	}

	/**
	 * Deduct resources from this player's inventory
	 * 
	 * @param type   Type of resource to deduct
	 * @param amount Amount to deduct
	 */
	public void deductResource(ResourceType type, int amount) {
		int current = resources.get(type);
		resources.put(type, Math.max(0, current - amount));
	}

	/**
	 * Get the quantity of a specific resource
	 * 
	 * @param type Resource type to query
	 * @return Quantity of that resource
	 */
	public int getResourceCount(ResourceType type) {
		return resources.get(type);
	}

	/**
	 * Get the total number of resource cards held by this player
	 * 
	 * @return Total resource card count
	 */
	public int getTotalResourceCards() {
		return resources.values().stream().mapToInt(Integer::intValue).sum();
	}

	/**
	 * Check if player has sufficient resources for a given cost
	 * 
	 * @param cost Map of resource types to required quantities
	 * @return true if player has all required resources, false otherwise
	 */
	public boolean hasResources(Map<ResourceType, Integer> cost) {
		for (Map.Entry<ResourceType, Integer> entry : cost.entrySet()) {
			if (resources.get(entry.getKey()) < entry.getValue()) {
				return false;
			}
		}
		return true;
	}

	/**
	 * Abstract method for player to take their turn
	 * 
	 * @param controller Game controller interface for making moves
	 */
	public abstract void takeTurn(IGameController controller);

	/**
	 * Abstract method for handling situation when player has more than 7 cards
	 */
	public abstract void handleOverSevenCards();

	/**
	 * Abstract method for discarding cards when the robber is activated.
	 * Called when a 7 is rolled and the player has more than 7 cards.
	 * 
	 * @param amountToDrop The number of cards the player must discard
	 */
	public abstract void robberDiscard(int amountToDrop);

	/**
	 * Get a copy of the player's resources
	 * 
	 * @return Defensive copy of the resources map
	 */
	public Map<ResourceType, Integer> getResources() {
		return new HashMap<>(resources);
	}

	/**
	 * Steal a random resource from this player.
	 * Removes one card of a random resource type and returns the type stolen.
	 * 
	 * @return The ResourceType that was stolen, or null if the player has no
	 *         resources
	 */
	public ResourceType stealRandomResource() {
		if (getTotalResourceCards() == 0) {
			return null;
		}

		// Collect resource types that have at least 1 card
		List<ResourceType> available = new ArrayList<>();
		for (ResourceType type : ResourceType.values()) {
			if (getResourceCount(type) > 0) {
				available.add(type);
			}
		}

		if (available.isEmpty()) {
			return null;
		}

		// Pick a random resource type and remove 1
		Random random = new Random();
		ResourceType stolen = available.get(random.nextInt(available.size()));
		deductResource(stolen, 1);
		return stolen;
	}
}
