// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.mycompany.app;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

/************************************************************/
/**
 * Simulator orchestrates the game flow, managing rounds and player turns
 */
public class Simulator {
	/**
	 * The game engine
	 */
	private CatanEngine engine;
	/**
	 * List of players (3-4 players)
	 */
	private List<Player> players;
	/**
	 * Current round number
	 */
	private int currRound;
	/**
	 * Maximum number of rounds to simulate
	 */
	private int maxRounds;
	/**
	 * Shared scanner for console input (step-forward)
	 */
	private final Scanner stepScanner;


	/**
	 * Constructor for Simulator
	 * 
	 * @param maxRounds Maximum number of rounds to run (1-8192)
	 */
	public Simulator(int maxRounds) {
		this(maxRounds, new Scanner(System.in));
	}

	/**
	 * Constructor for Simulator with injected input (useful for tests).
	 *
	 * @param maxRounds Maximum number of rounds to run (1-8192)
	 * @param scanner Shared scanner for step-forward + human input
	 */
	public Simulator(int maxRounds, Scanner scanner) {
		this.stepScanner = scanner;
		
		// Create board with topology
    	IBoardGraph topology = new CatanBoardGraph();

    	Board board = new Board(topology);

		// Create dice
    	IRandomDice dice = new StandardDice();

		// Create engine
    	this.engine = new CatanEngine(board, dice);

    	this.players = new ArrayList<>();

    	players.add(new RandomAgent(0));
    	players.add(new RandomAgent(1));
    	players.add(new RandomAgent(2));
    	players.add(new RandomAgent(3));

    	engine.setPlayers(players);

    	new GameStateObserver(engine);

    	this.maxRounds = maxRounds;

    	this.currRound = 0;
	}

	/**
	 * Initial setup phase - hardcoded 2 settlements + 2 roads per player, then starting resources.
	 * Matches Catan rules: placement is free (no resource cost) and happens before any dice rolls.
	 */
	private void initialSetup() {
		Board board = engine.getBoard();

		// Player 0 (RED): settlements at 0, 11; roads at 5, 13
		Player p0 = players.get(0);
		board.getNode(0).buildSettlement(p0);
		board.getNode(11).buildSettlement(p0);
		board.getEdge(5).buildRoad(p0);
		board.getEdge(13).buildRoad(p0);
		p0.addVictoryPoints(2);

		// Player 1 (BLUE): settlements at 3, 39; roads at 2, 52
		Player p1 = players.get(1);
		board.getNode(3).buildSettlement(p1);
		board.getNode(39).buildSettlement(p1);
		board.getEdge(2).buildRoad(p1);
		board.getEdge(52).buildRoad(p1);
		p1.addVictoryPoints(2);

		// Player 2 (ORANGE): settlements at 15, 27; roads at 19, 35
		Player p2 = players.get(2);
		board.getNode(15).buildSettlement(p2);
		board.getNode(27).buildSettlement(p2);
		board.getEdge(19).buildRoad(p2);
		board.getEdge(35).buildRoad(p2);
		p2.addVictoryPoints(2);

		// Player 3 (WHITE): settlements at 22, 46; roads at 29, 64
		Player p3 = players.get(3);
		board.getNode(22).buildSettlement(p3);
		board.getNode(46).buildSettlement(p3);
		board.getEdge(29).buildRoad(p3);
		board.getEdge(64).buildRoad(p3);
		p3.addVictoryPoints(2);

		// Give each player starting resources for additional builds
		for (Player player : players) {
			player.addResource(ResourceType.LUMBER, 4);
			player.addResource(ResourceType.BRICK, 4);
			player.addResource(ResourceType.GRAIN, 2);
			player.addResource(ResourceType.WOOL, 2);
			player.addResource(ResourceType.ORE, 2);
		}

		engine.notifyObservers();
		System.out.println("Initial setup: 2 settlements + 2 roads per player placed; starting resources granted.");
	}

	/**
	 * Run the complete simulation
	 */
	public void runSimulation() {
		// Initial setup
		initialSetup();

		// Main game loop
		while (currRound < maxRounds) {
			currRound++;
			System.out.println("\n=== Round " + currRound + " ===");

			// Each player takes a turn
			for (Player player : players) {
				System.out.println("[" + currRound + "] / [" + player.getPlayerID() + "]: Ready to take turn.");
				waitForGo();

				// Roll dice
				int roll = engine.rollDice();
				System.out.println("[" + currRound + "] / [" + player.getPlayerID() + "]: Rolled " + roll);

				// Handle robber on 7
				if (roll == 7) {
					System.out.println(
							"[" + currRound + "] / [" + player.getPlayerID() + "]: Rolled 7, no resources produced");

					engine.handleRollSeven(player);
				} else {
					// Distribute resources
					engine.distributeResources(roll, players);

					// Log resource collection
					int totalCollected = 0;
					for (Player p : players) {
						// Count resources this player collected (simplified)
						if (p.getTotalResourceCards() > 0) {
							totalCollected++;
						}
					}
				}

				// Player takes turn (attempts to build)
				player.takeTurn(engine);
				System.out.println("[" + currRound + "] / [" + player.getPlayerID() + "]: Turn finished.");

				// Check for victory
				if (player.getVictoryPoints() >= 10) {
					System.out.println("[" + currRound + "] / [" + player.getPlayerID()
							+ "]: Reached 10 victory points! Game over.");
					printFinalScores();
					return; // Terminate
				}
			}

			// End of round: print victory points
			printRoundScores();
		}

		// Max rounds reached
		System.out.println("\nMaximum rounds reached. Game over.");
		printFinalScores();
	}

	/**
	 * Print victory points at end of each round
	 */
	private void printRoundScores() {
		StringBuilder sb = new StringBuilder("End of round " + currRound + ": ");
		for (int i = 0; i < players.size(); i++) {
			sb.append("Player ").append(i).append(": ")
					.append(players.get(i).getVictoryPoints()).append(" VP");
			if (i < players.size() - 1) {
				sb.append(", ");
			}
		}
		System.out.println(sb.toString());
	}

	/**
	 * Print final scores at game end
	 */
	private void printFinalScores() {
		System.out.println("\n=== Final Scores ===");
		for (Player player : players) {
			System.out.println("Player " + player.getPlayerID() + ": " +
					player.getVictoryPoints() + " victory points");
		}
	}

	/**
	 * Wait for the user to type 'go' before proceeding to the next turn.
	 * Implements the step-forward functionality (R2.4).
	 * 
	 * @param player The player whose turn is about to begin
	 */
	private void waitForGo(Player player) {
		System.out.println("\nType 'go' to proceed to Player " + player.getPlayerID() + "'s turn...");
		while (stepScanner.hasNextLine()) {
			String input = stepScanner.nextLine().trim();
			if (input.equalsIgnoreCase("go")) {
				break;
			}
		}
	}


	private void waitForGo() {
		while (true) {
			System.out.print("Type 'go' to proceed: ");
			String line;
			try {
				line = stepScanner.nextLine();
			} catch (Exception e) {
				return;
			}
			if (line != null && line.trim().equalsIgnoreCase("go")) {
				return;
			}
			System.out.println("Unrecognized input. Please type exactly 'go'.");
		}
	}
}
