// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package main.java.com.mycompany.app;

import java.util.ArrayList;
import java.util.List;

/************************************************************/
/**
 * Simulator orchestrates the game flow, managing rounds and player turns
 */
public class Simulator {
	/**
	 * The game engine
	 */
	private CatanEngine engine;
	/**
	 * List of players (3-4 players)
	 */
	private List<Player> players;
	/**
	 * Current round number
	 */
	private int currRound;
	/**
	 * Maximum number of rounds to simulate
	 */
	private int maxRounds;

	/**
	 * Constructor for Simulator
	 * @param maxRounds Maximum number of rounds to run (1-8192)
	 */
	public Simulator(int maxRounds) {
		// Create board with topology
		IBoardGraph topology = new CatanBoardGraph();
		Board board = new Board(topology);

		// Create dice
		IRandomDice dice = new StandardDice();

		// Create engine
		this.engine = new CatanEngine(board, dice);

		// Create 4 random agents
		this.players = new ArrayList<>();
		for (int i = 0; i < 4; i++) {
			players.add(new RandomAgent(i));
		}

		engine.setPlayers(players);

		this.maxRounds = maxRounds;
		this.currRound = 0;
	}

	/**
	 * Initial setup phase - give each player starting resources and positions
	 */
	private void initialSetup() {
		// Give each player some starting resources for initial builds
		// This is a simplified initial setup
		for (Player player : players) {
			// Give starting resources (2 of each for initial builds)
			player.addResource(ResourceType.LUMBER, 4);
			player.addResource(ResourceType.BRICK, 4);
			player.addResource(ResourceType.GRAIN, 2);
			player.addResource(ResourceType.WOOL, 2);
			player.addResource(ResourceType.ORE, 2);
		}

		System.out.println("Initial setup: Each player receives starting resources");
	}

	/**
	 * Run the complete simulation
	 */
	public void runSimulation() {
		// Initial setup
		initialSetup();

		// Main game loop
		while (currRound < maxRounds) {
			currRound++;

			// Each player takes a turn
			for (Player player : players) {
				// Roll dice
				int roll = engine.rollDice();
				System.out.println("[" + currRound + "] / [" + player.getPlayerID() + "]: Rolled " + roll);

				// Handle robber on 7
				if (roll == 7) {
					System.out.println("[" + currRound + "] / [" + player.getPlayerID() + "]: Rolled 7, no resources produced");

					// Each player with >7 cards must handle it
					for (Player p : players) {
						if (p.getTotalResourceCards() > 7) {
							System.out.println("[" + currRound + "] / [" + p.getPlayerID() + "]: Has " + p.getTotalResourceCards() + " cards, attempting to build...");
							p.handleOverSevenCards();
						}
					}
				} else {
					// Distribute resources
					engine.distributeResources(roll, players);

					// Log resource collection
					int totalCollected = 0;
					for (Player p : players) {
						// Count resources this player collected (simplified)
						if (p.getTotalResourceCards() > 0) {
							totalCollected++;
						}
					}
				}

				// Player takes turn (attempts to build)
				player.takeTurn(engine);

				// Check for victory
				if (player.getVictoryPoints() >= 10) {
					System.out.println("[" + currRound + "] / [" + player.getPlayerID() + "]: Reached 10 victory points! Game over.");
					printFinalScores();
					return; // Terminate (R1.5)
				}
			}

			// End of round: print victory points (R1.7)
			printRoundScores();
		}

		// Max rounds reached
		System.out.println("\nMaximum rounds reached. Game over.");
		printFinalScores();
	}

	/**
	 * Print victory points at end of each round
	 */
	private void printRoundScores() {
		StringBuilder sb = new StringBuilder("End of round " + currRound + ": ");
		for (int i = 0; i < players.size(); i++) {
			sb.append("Player ").append(i).append(": ")
			  .append(players.get(i).getVictoryPoints()).append(" VP");
			if (i < players.size() - 1) {
				sb.append(", ");
			}
		}
		System.out.println(sb.toString());
	}

	/**
	 * Print final scores at game end
	 */
	private void printFinalScores() {
		System.out.println("\n=== Final Scores ===");
		for (Player player : players) {
			System.out.println("Player " + player.getPlayerID() + ": " +
				player.getVictoryPoints() + " victory points");
		}
	}
}
