// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.mycompany.app;

/************************************************************/
/**
 * 
 */
public enum TileType {
	/**
	 * 
	 */
	WOOD,
	/**
	 * 
	 */
	BRICK,
	/**
	 * 
	 */
	WHEAT,
	/**
	 * 
	 */
	SHEEP,
	/**
	 * 
	 */
	ORE,
	/**
	 *
	 */
	DESERT;

	/**
	 * Get the resource type produced by this tile type
	 * @return ResourceType, or null for DESERT
	 */
	public ResourceType getResourceType() {
		switch (this) {
			case WOOD: return ResourceType.LUMBER;
			case BRICK: return ResourceType.BRICK;
			case WHEAT: return ResourceType.GRAIN;
			case SHEEP: return ResourceType.WOOL;
			case ORE: return ResourceType.ORE;
			case DESERT: return null;
			default: return null;
		}
	}
}
