// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package UMLDesign.CatanProject.com.mycompany.app;

/************************************************************/
/**
 * 
 */
public class ActionLogger {
	/**
	 * Log an action to console in the specified format: [round] / [playerID]: action @param round Current round number @param playerID Player taking the action @param action Description of the action taken
	 * @param round 
	 * @param playerID 
	 * @param action 
	 */
	public void logAction(Integer round, Integer playerID, String action) {
		
	}
}