// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package UMLDesign.CatanProject.com.mycompany.app;

import java.util.Map;

/************************************************************/
/**
 * 
 */
public enum BuildingCost {
	/**
	 * 
	 */
	ROAD,
	/**
	 * 
	 */
	SETTLEMENT,
	/**
	 * 
	 */
	CITY
	;
	/**
	 * 
	 */
	private final Map cost;
	/**
	 * 
	 * @param cost 
	 */
	private BuildingCost(Map cost) {

	}
	/**
	 * Get the resource cost for this building type @return Immutable map of resource types to quantities
	 * @return 
	 */
	public Map getCost() {

	}
	/**
	 * Get the victory points awarded for this building @return Victory points (SETTLEMENT=1, CITY=2, ROAD=0)
	 * @return 
	 */
	public Integer getVictoryPoints() {

	}
}
