// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package UMLDesign.CatanProject.com.mycompany.app;

/************************************************************/
/**
 * 
 */
public class HexTile {
	/**
	 * Unique identifier for this tile
	 */
	private Integer tileID;
	/**
	 * Type of resource this tile produces
	 */
	private TileType type;
	/**
	 * Number token on this tile (2-12, or 0 for desert)
	 */
	private Integer numberToken;

	/**
	 * Constructor for HexTile @param tileID Unique tile identifier @param type Resource type of this tile @param numberToken Number token (2-12, or 0 for desert)
	 * @param tileID 
	 * @param type 
	 * @param numberToken 
	 */
	public HexTile(Integer tileID, TileType type, Integer numberToken) {
		
	}

	/**
	 * Get the tile ID @return The tile's unique identifier
	 * @return 
	 */
	public Integer getTileID() {
		
	}

	/**
	 * Get the tile type @return The resource type of this tile
	 * @return 
	 */
	public TileType getType() {
		
	}

	/**
	 * Get the number token @return The number token on this tile
	 * @return 
	 */
	public Integer getNumberToken() {
		
	}
}