// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package UMLDesign.CatanProject.com.mycompany.app;

/************************************************************/
/**
 * 
 */
public interface IBoardGraph {
	/**
	 * @param nodeID  @return
	 * @return 
	 * @param nodeID 
	 */
	public Integer[] getAdjacentNodes(Integer nodeID);

	/**
	 * @param nodeID @return
	 * @return 
	 * @param nodeID 
	 */
	public Integer[] getAdjacentEdges(Integer nodeID);

	/**
	 * Get the two endpoint nodes of an edge @param edgeID The edge identifier @return Array of two node IDs, or empty array if not found
	 * @return 
	 * @param edgeID 
	 */
	public Integer[] getEdgeEndpoints(Integer edgeID);

	/**
	 * Get nodes adjacent to a specific tile @param tileID The tile identifier (0-18) @return Array of node IDs surrounding this tile
	 * @return 
	 * @param tileID 
	 */
	public Integer[] getTileNodes(Integer tileID);
}