// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package UMLDesign.CatanProject.com.mycompany.app;

/************************************************************/
/**
 * 
 */
public interface IGameController {
	/**
	 * @param playerID  @return
	 * @return 
	 * @param playerID 
	 */
	public Integer[] getValidSettlementLocations(Integer playerID);

	/**
	 * @param playerID  @return
	 * @return 
	 * @param playerID 
	 */
	public Integer[] getValidRoadLocations(Integer playerID);

	/**
	 * @param playerID  @param nodeID  @return
	 * @return 
	 * @param playerID 
	 * @param nodeID 
	 */
	public Boolean requestBuildSettlement(Integer playerID, Integer nodeID);

	/**
	 * @param playerID  @param edgeID  @param Parameter1
	 * @return 
	 * @param playerID 
	 * @param edgeID 
	 */
	public Boolean requestBuildRoad(Integer playerID, Integer edgeID);
}