// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package UMLDesign.CatanProject.com.mycompany.app;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * Unique identifier for this node
	 */
	private Integer nodeID;
	/**
	 * Type of building on this node (NONE, SETTLEMENT, or CITY)
	 */
	private BuildingType type;
	/**
	 * Player who owns the building on this node (null if unoccupied)
	 */
	private Player occupant;

	/**
	 * Constructor for Node @param nodeID Unique node identifier
	 * @param nodeID 
	 */
	public Node(Integer nodeID) {
		
	}

	/**
	 * Get the node ID @return The node's unique identifier
	 * @return 
	 */
	public Integer getNodeID() {
		
	}

	/**
	 * Get the building type on this node @return The type of building (NONE, SETTLEMENT, or CITY)
	 * @return 
	 */
	public BuildingType getType() {
		
	}

	/**
	 * Get the occupying player @return The player who owns the building, or null if unoccupied
	 * @return 
	 */
	public Player getOccupant() {
		
	}

	/**
	 * Set the occupant and building type on this node @param p Player who will occupy this node @param t Type of building to place
	 * @param p 
	 * @param t 
	 */
	public void setOccupant(Player p, BuildingType t) {
		
	}

	/**
	 * Check if this node is occupied by any player @return true if there's a building on this node
	 * @return 
	 */
	public Boolean isOccupied() {
		
	}

	/**
	 * Check if this node is occupied by a specific player @param playerID The player ID to check @return true if this player occupies this node
	 * @return 
	 * @param playerID 
	 */
	public Boolean isOccupiedBy(Integer playerID) {
		
	}

	/**
	 * Build a settlement on this node @param player The player building the settlement
	 * @param player 
	 */
	public void buildSettlement(Player player) {
		
	}

	/**
	 * Upgrade settlement to city on this node @param player The player upgrading (must already own settlement)
	 * @param player 
	 */
	public void upgradeToCity(Player player) {
		
	}

	/**
	 * Check if this is a settlement owned by the given player @param playerID The player ID to check @return true if this node has a settlement owned by the player
	 * @return 
	 * @param playerID 
	 */
	public Boolean hasSettlementBy(Integer playerID) {
		
	}
}