// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package UMLDesign.CatanProject.com.mycompany.app;

/************************************************************/
/**
 * Random agent that makes random valid moves each turn
 */
public class RandomAgent extends Player {
	/**
	 * 
	 */
	private Random random;

	/**
	 * Constructor for RandomAgent @param playerID Unique player identifier
	 * @param playerID 
	 */
	public RandomAgent(Integer playerID) {
		
	}

	/**
	 * Take a turn by making random valid moves @param controller Game controller interface
	 * @param controller 
	 */
	public void takeTurn(IGameController controller) {
		
	}

	/**
	 * Handle having more than 7 cards by attempting to build
	 */
	public void handleOverSevenCards() {
		
	}
}
