// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package UMLDesign.CatanProject.com.mycompany.app;

/************************************************************/
/**
 * 
 */
public enum ResourceType {
	/**
	 * 
	 */
	LUMBER,
	/**
	 * 
	 */
	BRICK,
	/**
	 * 
	 */
	GRAIN,
	/**
	 * 
	 */
	WOOL,
	/**
	 * 
	 */
	ORE;
}