// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package UMLDesign.CatanProject.com.mycompany.app;

import java.util.Random;

/************************************************************/
/**
 * Standard implementation of IRandomDice that simulates rolling two six-sided dice. Returns values between 2 and 12 (inclusive).
 */
public class StandardDice implements IRandomDice {
	/**
	 * 
	 */
	private Random random;

	/**
	 * Constructor for StandardDice
	 */
	public StandardDice() {
		
	}

	/**
	 * Rolls two six-sided dice and returns the sum @return The sum of two dice rolls (2-12)
	 * @return 
	 */
	public Integer roll() {
		
	}
}