// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package UMLDesign.CatanProject.com.mycompany.app;

/************************************************************/
/**
 * Demonstrator class - Main entry point for the Catan simulator Runs a sample simulation demonstrating the game mechanics
 */
public class Demonstrator {
	/**
	 * Main entry point @param args Command line arguments (unused)
	 * @param args 
	 */
	public static void main(String[] args) {
		
	}
}
