// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanProject;
import java.util.*;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	private Map<Integer, HexTile> tiles;
	/**
	 * 
	 */
	private Map<Integer, Node>  nodes;
	/**
	 * 
	 */
	private Map<Integer, Edge> edges;
	/**
	 * 
	 */
	private IBoardGraph topology;
	/**
	 * 
	 */
	public IBoardGraph iboardgraph;
	/**
	 * 
	 */
	public HexTile hextile;
	/**
	 * 
	 */
	public Node node;
	/**
	 * 
	 */
	public Edge edge;

	/**
	 * 
	 * @param topoology 
	 */
	public void Board(IBoardGraph topoology) {
	}

	/**
	 * 
	 * @param nodeID 
	 * @return 
	 */
	public Node getNode(int nodeID) {
	}

	/**
	 * 
	 * @param edgeID 
	 * @return 
	 */
	public Edge getEdge(int edgeID) {
	}
}
