// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanProject;

/************************************************************/
/**
 * 
 */
public class CatanEngine implements IGameController {
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private IRandomDice dice;
	/**
	 * 
	 */
	private ActionLogger logger;
	/**
	 * 
	 */
	public IRandomDice irandomdice;
	/**
	 * 
	 */
	public Board game_board;
	/**
	 * 
	 */
	public ActionLogger actionlogger;

	/**
	 * 
	 * @param playerID 
	 * @return 
	 */
	public int[] getValidSettlementLocations(int playerID) {
	}

	/**
	 * 
	 * @param playerID 
	 * @param nodeID 
	 * @return 
	 */
	public boolean requestBuildSettlement(int playerID, int nodeID) {
	}

	/**
	 * 
	 * @param playerID 
	 * @param cost 
	 */
	public void deductResources(int playerID, EMap cost) {
	}
}
