// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanProject;
import java.util.*;

/************************************************************/
/**
 * 
 */
public class CatanEngine implements IGameController {
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private IRandomDice dice;
	/**
	 * 
	 */
	private ActionLogger logger;
	/**
	 * 
	 */
	public IRandomDice irandomdice;
	/**
	 * 
	 */
	public Board game_board;
	/**
	 * 
	 */
	public ActionLogger actionlogger;

	/**
	 * 
	 * @param playerID 
	 * @return 
	 */
	public int[] getValidSettlementLocations(int playerID) {
		return null;
	}

	/**
	 * 
	 * @param playerID 
	 * @param nodeID 
	 * @return 
	 */
	public boolean requestBuildSettlement(int playerID, int nodeID) {
		return false;
	}

	/**
	 * 
	 * @param playerID 
	 * @param cost 
	 */
	public void deductResources(int playerID, Map<ResourceType, Integer> cost) {
	}

	public boolean requestBuildRoad(int playerID, int edgeID) {
		return false;
	}

	public int[] getValidRoadLocations(int playerID) {
		return null;
	}


}
