// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanProject;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	private int nodeID;
	/**
	 * 
	 */
	private BuildingType type;
	/**
	 * 
	 */
	private Player occupant;

	/**
	 * 
	 * @param p 
	 * @param t 
	 */
	public void setOccupant(Player p, BuildingType t) {
	}
}
