// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanProject;

import java.util.Map;

/************************************************************/
/**
 * 
 */
public abstract class Player {
	/**
	 * 
	 */
	protected int playerID;
	/**
	 * 
	 */
	protected int victoryPoints;
	/**
	 * 
	 */
	protected Map<ResourceType, Integer> resources;

	/**
	 * 
	 * @return 
	 */
	public int getPlayerID() {
	}

	/**
	 * 
	 * @param controller 
	 */
	public abstract void takeTurn(IGameController controller);

	/**
	 * 
	 */
	public abstract void handleOverSevenCards();
}
