// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanProject;

/************************************************************/
/**
 * 
 */
public class RandomAgent extends Player {
	/**
	 * 
	 * @param controller 
	 */
	public void takeTurn(IGameController controller) {
	}

	/**
	 * 
	 */
	public void handleOverSevenCards() {
	}
}
