// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanProject;

/************************************************************/
/**
 * 
 */
public class Simulator {
	/**
	 * 
	 */
	private CatanEngine engine;
	/**
	 * 
	 */
	private Player[] players;
	/**
	 * 
	 */
	private int currRound;
	/**
	 * 
	 */
	public Player[] player;
	/**
	 * 
	 */
	public CatanEngine catanengine;

	/**
	 * 
	 */
	public void runSimulation() {
	}
}
